image: node:latest

stages:
  - install
  - build

install-frontend:
  stage: install
  script:
    - cd frontend && npm install
  artifacts:
    paths:
      - node_modules/
  when: manual

build-frontend:
  stage: build
  script:
    - CI=false cd frontend && npm run build
  artifacts:
    paths:
      - build
  when: manual
