image: docker:stable

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  BASE_IMAGE_URL: gcr.io/studied-reason-400621
  FRONTEND_IMAGE: frontend
  AUTH_IMAGE: service/auth
  UPLOAD_IMAGE: service/upload

stages:
  - publish

before_script:
  # Install CA certs, openssl to https downloads, python for gcloud sdk
  - apk update
  - apk add make ca-certificates openssl python3 curl bash
  - update-ca-certificates
  - curl -s https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer | bash
  # Download and install Google Cloud SDK
  - wget https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.tar.gz
  - tar xzf google-cloud-sdk.tar.gz && ./google-cloud-sdk/install.sh --usage-reporting=false --path-update=true
  - google-cloud-sdk/bin/gcloud --quiet components update
  - google-cloud-sdk/bin/gcloud auth activate-service-account --key-file .secure_files/studied-reason-400621-99e97160ca02.json
  - google-cloud-sdk/bin/gcloud auth configure-docker
  - cat .secure_files/studied-reason-400621-99e97160ca02.json | docker login -u _json_key --password-stdin https://gcr.io


publish:
  stage: publish
  script:
    - echo "$BASE_IMAGE_URL/$FRONTEND_IMAGE"
    - docker build -t "$BASE_IMAGE_URL/$FRONTEND_IMAGE" frontend/.
    - docker push $BASE_IMAGE_URL/$FRONTEND_IMAGE
    - openssl genpkey -algorithm RSA -out priv.pem
    - openssl rsa -pubout -in priv.pem -out pub.pem
    - cp priv.pem services/auth/
    - cp pub.pem services/upload/
    - docker build -t $BASE_IMAGE_URL/$AUTH_IMAGE services/auth/.
    - docker push $BASE_IMAGE_URL/$AUTH_IMAGE
    - docker build -t $BASE_IMAGE_URL/$UPLOAD_IMAGE services/upload/.
    - docker push $BASE_IMAGE_URL/$UPLOAD_IMAGE
  only:
    - master