---
- hosts: targets
  become: yes
  become_method: sudo
  gather_facts: True
  remote_user: ubuntu

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Log into Google Cloud
      docker_login:
        registry: https://gcr.io
        username: _json_key
        debug: true
        password: " {{ lookup('file', '/home/vagrant/infra/studied-reason-400621-7f66018600a2.json')}}"
    
    - name: Pull Docker container from GCR
      docker_container:
        name: "container"
        image: "{{ container_name }}"
        pull: yes
        state: started
        restart_policy: always

- hosts: frontend
  become: yes
  become_method: sudo
  gather_facts: True
  remote_user: ubuntu
  
  tasks:
    - name: Run frontend container
      docker_container:
        name: "container"
        image: "{{ container_name }}"
        pull: yes
        state: started
        restart_policy: always
        ports:
          - "80:80"